# Generated by Django 4.2.9 on 2024-02-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('balance', models.IntegerField(default=0)),
                ('modifiedDate', models.DateTimeField(verbose_name='last update')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(default=0)),
                ('debit', models.IntegerField(default=0)),
                ('modifiedDate', models.DateTimeField(verbose_name='transaction date time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
    ]
